
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl

  jpa:
 #   hibernate:
#      ddl-auto: update # 数据库连接必备的参数？
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop #自动创建、更新、验证数据库表结构
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: cn.sf.springbootdemo.entity
